
# === EXACT COPY OF YOUR RAW_KEEP_V1_SCHEMA (AS OUTPUT SCHEMA) ===
INCIDENTS_RAW_KEEP_V1_SCHEMA: dict[str, str] = {
    "INCIDENT_ID": "INCIDENT_ID", 

    "ORI": "ORI",
    "INCNUM": "INCNUM",
    "INCDATE": "INCDATE",

    "V20071": "OFFENSE_SEQ_NUM",
    "V20061": "OFFENSE_CODE",
    "V20072": "ATTEMPTED_COMPLETED",
    "V20171": "WEAPON_CODE",
    "V20091": "BIAS_MOTIVATION",

    "STATE": "STATE",
    "FIPS_STATE": "FIPS_STATE",
    "YEAR": "YEAR",
    "RELEASE": "RELEASE",
}

